name: Selenium Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install backend
      - name: Install backend
        working-directory: backend
        run: npm install

      # Install frontend
      - name: Install frontend
        working-directory: frontend-new
        run: npm install

      # Install tests
      - name: Install tests
        working-directory: e2e-tests
        run: npm install

      # Start backend
      - name: Start backend
        working-directory: backend
        run: npm start &

      # Wait for backend (PORT 5001)
      - name: Wait for backend
        run: npx wait-on http://127.0.0.1:5001/api/auth/me
        
      # Start frontend
      - name: Start frontend
        working-directory: frontend-new
        run: npm run dev -- --host 0.0.0.0 &

      # Wait for frontend
      - name: Wait for frontend
        run: npx wait-on http://localhost:5173/Samadhan/

      # Run tests
      - name: Run tests
        working-directory: e2e-tests
        run: npm test
